### ISSUE TITLE
No keyboard/mouse past UEFI

### ISSUE THREAD

**Issue by pedrospinto** [andreiw/lampone#3]
Hi Andrei,

I've built the firmware in Ubuntu without issues using this script. RPI4 loads UEFI ok and shows the full 4096MB.
I'm powering the pi through a PiUART addon board, to free the USB-C port. This way I can bypass the (as yet inoperative) PCI-Express bus and plug keyboard/mouse and extra storage devices in.
Works just fine. I can enter UEFI, navigate the menus and see the storage devices I connect to the USB hub.
With this setup, I put the Arm64 Windows 10 installation image into a USB drive (using Rufus) and am able to boot it up and reach the first screen (where one selects language, time/currency format and keyboard layout). However, at that point I don't have keyboard or mouse, even though keyboard was operational at bootup. Any idea why this is?
Congrats on your fantastic work.

Pedro

**Comment by andreiw** [comment]
So uh... first of all - congratulations. I think you're the first person ever in the world - seriously - to have booted Windows 10 on a Raspberry Pi 4. That calls for a celebration all by itself.

The reason your keyboard/mouse don't work is because you're missing the DWC2 driver in Windows. Try the one MCCI made available here - https://pi64.win/download-usb-drivers/.

**Comment by pedrospinto** [comment]
First boot ever, for real? LOL, now I'm celebrating!
I've added the drivers you mentioned to boot.wim but still no keyboard/mouse. Something else must be missing.
Anyway, here's a video of the momentous occasion for you to check out :)
https://youtu.be/xLginVnIggE

**Comment by andreiw** [comment]
Do you happen to have a 1G board to try your image (with MCCI drivers) on?

**Comment by pedrospinto** [comment]
I don't, unfortunately. If it really helps you pinpoint the issue, I can go and buy one...

**Comment by andreiw** [comment]
Let me cut you a build that will force 1G...

A

**Comment by ShireCiel** [comment]
You can install windows 10 using "win to go". After installed in your device. You can try mount your boot device in qemu arm. And install install driver what you want in VM.

Could you put your boot files up? (Include start.elf, fixup.dat and bootcode.bin)
I build RPI_EFI.fd using this script, and downloaded lasted [start.elf, fixup.dat and bootcode.bin] from  "https://github.com/raspberrypi/firmware/tree/master/boot". Just got black screen. I try both two hdmi same with that. Can i try your boot files?

**Comment by pedrospinto** [comment]
ShireCiel, going a bit off-topic here.
Probably it's your boot partition that isn't correctly configured. I bet the green light on your Pi is blinking, four flashes at a time.
Make sure it's formatted as FAT32. Also make sure that its type ID is correct. You can do this on Ubuntu using Gparted, manage the partition flags, select BOOT and LBA flags.

**Comment by ShireCiel** [comment]
> partition

My tf card just installed linux of raspberry. It can normally boot to linux. I just replace RPI_EFI.fd and config on that boot partition. Green light on my Pi is long light and turn off in seconds.
So I think maybe some differences between ours boot files.
= = So, could you put your boot files up and let me try.

**Comment by pedrospinto** [comment]
Here, this is enough to boot into UEFI:
https://we.tl/t-95aWWScVwY

**Comment by ShireCiel** [comment]
> Here, this is enough to boot into UEFI:
> https://we.tl/t-95aWWScVwY

Thanks.
Successful boot up to UEFI using your boot files.
I check diff between yours files and mine.
The reason I cannot boot up is I deleted all file from boot partition and just download (start.elf, fixup.dat and bootcode.bin)  (read from RPI3 UEFI guide).
But it need all of fixup4*.dat and start4*.elf(fixup4.dat, fixup4cd.dat, fixup4db.dat, fixup4x.dat, start4.elf, start4cd.elf, start4db.elf, start4x.elf) on RPI4. (Missing these files will not "blinking, four flashes at a time", just "long light and turn off in seconds.". Looks like loaded something but not boot up)
I tried using my RPI_EFI.fd with these boot files, it successful boot up to UEFI.
RPI_EFI.fd of this script builded is ok just missing these boot files.

**Comment by ShireCiel** [comment]
Same with pedrospinto. I have already installed driver from "https://pi64.win/download-usb-drivers/" to boot.wim. It enter to first screen of install, cannot control any keyboard or mouse.
I also using dism apply image to tf card. But get "INACCESSIBLE BOOT DEVICE" error. I tried boot from a usb devices, same error with that. (I already added pi3's “SD/SDIO Host Controller” driver.)

**Comment by andreiw** [comment]
Closing as a non-firmware issue
