### ISSUE TITLE
meet some package require errors

### ISSUE THREAD

**Issue by ShireCiel** [andreiw/lampone#4]
error
`fatal error: uuid/uuid.h: No such file or directory`
need require
`apt-get install uuid-dev`

error:
```
/bin/sh: 1: iasl: not found
GNUmakefile:353: recipe for target '/root/temp/pi4/rpi_fw/Build/RPi3/RELEASE_GCC5/AARCH64/Platform/RaspberryPi/RPi3/AcpiTables/AcpiTables/OUTPUT/Dsdt.aml' failed
make: *** [/root/temp/pi4/rpi_fw/Build/RPi3/RELEASE_GCC5/AARCH64/Platform/RaspberryPi/RPi3/AcpiTables/AcpiTables/OUTPUT/Dsdt.aml] Error 127
```
need require
`apt-get install iasl`
On my ubuntu 16.04 server these packages not installed by default.
Install those packages and fixed it.
Suggest add `apt-get update && apt-get install -y uuid-dev iasl` in shell script.

**Comment by andreiw** [comment]
Sure, it’s just that not everyone uses Debian/Ubuntu. But I’ll spell out the requirements.

**Comment by andreiw** [comment]
Added comment to script.
