### ISSUE TITLE
No Keyboard during UEFI boot

### ISSUE THREAD

**Issue by gowthamsiddarthd** [andreiw/lampone#5]
Hi Andreiw,

Thanks to your script I am able to successfully build UEFI for RPi4.
When I try to boot up, I have no access to key board.

I am able to get the Pi logo with options for setup, shell and boot. At this point I have no access to keyboard. Hence I am unable to select any option. I also get the message "BdsDxe: No bootable option or devices was found. BdsDxe: Press any key to enter the Boot Manager Menu." over the Pi logo and the loading is hung at that point.

I used all the boot files mentioned in the comments of https://github.com/andreiw/lampone/issues/3 and replaced the RPI_EFI.fd

Any idea on the issue?

I am using Raspberry Pi4 Model B 1GB RAM.
My goal is to run the SBSA test suite on Pi4.

Congrats on your fantastic work.

Regards,
Gowtham

**Comment by ShireCiel** [comment]
Hi.
UEFI for PI4 dose not support pci-e driver yet.
Usb hub on PI4  using pci interface conntect to cpu.
So you cannot using USB-A port in your Pi4.
But there is have other way to using usb devices.
The Pi4's type-c port support otg. You can using a type-c otg (or type-c to usb hub), and connect to power on GPIO pins(This way do not have any protect for power. If your power have any problem, It will destroy your device!!).

**Comment by gowthamsiddarthd** [comment]
Hi @ShireCiel,

Thanks a lot for the details. I am able to access the keyboard now.
Closing this issue as it is resolved.
