### ISSUE TITLE
Possibly Disable GICV2

### ISSUE THREAD

**Issue by n00b7** [andreiw/lampone#6]
When i try to boot windows 10 arm64 i get a uefi bios error and sometimes a unhandled interrupt error even in safe mode

**Comment by andreiw** [comment]
Thanks for your report. As usual, please provide build information and a screenshot (or any other text data seen, such as stop codes)

**Comment by n00b7** [comment]
Stop code: ACPI_BIOS_ERROR, lampone revision: d727a26d0f ,windows 10 revision: 19033, Raspberry Pi 4B

**Comment by n00b7** [comment]
Tried again with another build, boots fine in QEMU, but on pi 4 crashes with this error;
Stop code: INTERRUPT_EXCEPTION_NOT_HANDLED, lampone revision: d727a26d0f[same as first]  ,windows 10 revision: 18362, Raspberry Pi 4B
When i didnt get ACPI_BIOS_ERROR on ,windows 10 revision: 19033, i got INTERRUPT_EXCEPTION_NOT_HANDLED instead so i think this is the issue
Could this be because i'm booting off a usb?

**Comment by n00b7** [comment]
Is it because im booting over a usb?

**Comment by andreiw** [comment]
Hard to say at this point. Windows right now is not a priority.

A

**Comment by n00b7** [comment]
Yes considering the linux distro’s won’t even support the keyboard right now

**Comment by andreiw** [comment]
That’s being worked on now

A

**Comment by ShireCiel** [comment]
> Tried again with another build, boots fine in QEMU, but on pi 4 crashes with this error;
> Stop code: INTERRUPT_EXCEPTION_NOT_HANDLED, lampone revision: d727a26d0f[same as first] ,windows 10 revision: 18362, Raspberry Pi 4B
> When i didnt get ACPI_BIOS_ERROR on ,windows 10 revision: 19033, i got INTERRUPT_EXCEPTION_NOT_HANDLED instead so i think this is the issue
> Could this be because i'm booting off a usb?

"INTERRUPT_EXCEPTION_NOT_HANDLED"  may because windows not support usb and tfcard. I tried boot winpe on tfcard and usb deivce. It boot works fine, even could run some auto scripts, just cannot do any control from usb keyboard or mouse.

**Comment by n00b7** [comment]
Same thing when booting ftom an install usb which loads files to ram probably a GICv2 error, if it were an inaccessible drive the error should be INACCESSIBLE_BOOT_DEVICE, so how can i remove the GIC driver?
> "INTERRUPT_EXCEPTION_NOT_HANDLED" may because windows not support usb and tfcard. I tried boot winpe on tfcard and usb deivce. It boot works fine, even could run some auto scripts, just cannot do any control from usb keyboard or mouse.

**Comment by ShireCiel** [comment]
> Same thing when booting ftom an install usb which loads files to ram probably a GICv2 error, if it were an inaccessible drive the error should be INACCESSIBLE_BOOT_DEVICE, so how can i remove the GIC driver?
> 
> > "INTERRUPT_EXCEPTION_NOT_HANDLED" may because windows not support usb and tfcard. I tried boot winpe on tfcard and usb deivce. It boot works fine, even could run some auto scripts, just cannot do any control from usb keyboard or mouse.

I got INACCESSIBLE_BOOT_DEVICE error both in tf card and usb boot normal windows.
If your think INTERRUPT_EXCEPTION_NOT_HANDLED storage device works fine. You can try enable bootlog on bcdedit(you can google it for detail)
example:` bcdedit /store H:\EFI\Microsoft\Boot\BCD set {default} bootlog yes`.
If storage device accessible. It will create a file on "\Windows\ntbtlog.txt". Shows driver loaded when boot.
If there is no any log file created. Maybe just storage device not accessible, or boot process not arrive load drivers.

**Comment by ShireCiel** [comment]
> Same thing when booting ftom an install usb which loads files to ram probably a GICv2 error, if it were an inaccessible drive the error should be INACCESSIBLE_BOOT_DEVICE, so how can i remove the GIC driver?
> 
> > "INTERRUPT_EXCEPTION_NOT_HANDLED" may because windows not support usb and tfcard. I tried boot winpe on tfcard and usb deivce. It boot works fine, even could run some auto scripts, just cannot do any control from usb keyboard or mouse.

Is it you means cannot boot from windows 10 install media from usb?

**Comment by andreiw** [comment]
It’s not a GICv2 problem. Not supposed to work atm due to xHCI being not described in ACPI

A
